### ISSUE TITLE
Using Symlink for panel assets

### ISSUE THREAD

**Issue by kraftner** [fvsch/kirby-composerkit#1]
I've had a look at this boilerplate and it looks really nice, thanks for sharing your findings!

I've thought about the copying of the assets and came up with another solution for me. You can make things even simpler as long as you are on unix and not scared of symlinks:

Just change the scripts section of the composer.json to this:

```
"scripts": {
	"post-install-cmd": "@link-panel-assets",
	"post-update-cmd": "@link-panel-assets",
	"link-panel-assets": "ln -snf ../vendor/getkirby/panel/assets panel/assets"
}
```
This just symlinks the panel assets from the vendor folder into the expected location which replaces the whole `tools.php`.

I have just one final word of warning: Using the `-f` flag above is somewhat risky because it overwrites the target if it already exists. This is mostly great because the symlink might already exist and this way it gets overwritten without an error. But if the target `panel/assets` already exists, even if that is a file and not a symlink, it will get overwritten and you might lose something. Consult `man ln` for details :wink: Just wanted to mention that.

**Comment by fvsch** [comment]
We are not always on *nix, sadly. Many devs use Windows.

But NTFS has real symlinks since Vista (previously there were only junction points, which I've tried before but are no replacement for symlinks), and PHP can create them since PHP 5.3, so I could do that.

**Comment by kraftner** [comment]
Yeah, I am aware of that. That is also why I didn't make it a PR. I just wanted to mention it as an option as it hugely simplifies things.

**Comment by fvsch** [comment]
Fixed in https://github.com/fvsch/kirby-composerkit/commit/e2a40303f7ea656aaded6f9ea2ecb157af4d0491
